package nsd

import (
	"bytes"
	"fmt"
	"hash/fnv"
	"io"
	"log"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/sylgeist/dnstonetbox/model"
)

// Config holds NSD generator settings.
type Config struct {
	ZonesDir  string       `yaml:"zones_dir"`
	ReloadCmd string       `yaml:"reload_cmd"` // e.g. "nsd-control reload"
	Zones     []ZoneConfig `yaml:"zones"`
}

// ZoneConfig describes one authoritative DNS zone (forward or reverse).
type ZoneConfig struct {
	Name      string   `yaml:"name"`       // zone apex, e.g. "example.com" or "1.168.192.in-addr.arpa"
	TTL       int      `yaml:"ttl"`        // default 3600
	PrimaryNS string   `yaml:"primary_ns"` // FQDN with trailing dot
	NS        []string `yaml:"ns"`         // all NS FQDNs with trailing dots
	Email     string   `yaml:"email"`      // SOA rname with trailing dot
}

// ptrEntry holds a computed PTR record for a reverse zone template.
type ptrEntry struct {
	RelName string // relative name within the reverse zone (e.g. "10.1" or "1.0.0...0")
	Target  string // FQDN of the host with trailing dot
}

// --- templates ---

type forwardZoneData struct {
	Zone   ZoneConfig
	Hosts  []model.Host
	Serial string
}

type reverseZoneData struct {
	Zone   ZoneConfig
	PTRs   []ptrEntry
	Serial string
}

var forwardTmpl = template.Must(template.New("forward").Funcs(template.FuncMap{
	// relname returns the owner name relative to the zone apex, or "@".
	"relname": func(fqdn, zone string) string {
		if fqdn == zone {
			return "@"
		}
		if rel := strings.TrimSuffix(fqdn, "."+zone); rel != fqdn {
			return rel
		}
		return fqdn
	},
}).Parse(`; Generated by dnstonetbox — do not edit manually
$ORIGIN {{ .Zone.Name }}.
$TTL {{ .Zone.TTL }}

@ IN SOA {{ .Zone.PrimaryNS }} {{ .Zone.Email }} (
    {{ .Serial }} ; serial
    7200          ; refresh
    3600          ; retry
    1209600       ; expire
    {{ .Zone.TTL }} ) ; minimum
{{ range .Zone.NS }}
@ IN NS {{ . }}
{{- end }}
{{ range .Hosts }}
{{- if .IPv4 }}
{{ relname .Name $.Zone.Name }} IN A {{ .IPv4 }}
{{- end }}
{{- if .IPv6 }}
{{ relname .Name $.Zone.Name }} IN AAAA {{ .IPv6 }}
{{- end }}
{{ end }}`))

var reverseTmpl = template.Must(template.New("reverse").Parse(`; Generated by dnstonetbox — do not edit manually
$ORIGIN {{ .Zone.Name }}.
$TTL {{ .Zone.TTL }}

@ IN SOA {{ .Zone.PrimaryNS }} {{ .Zone.Email }} (
    {{ .Serial }} ; serial
    7200          ; refresh
    3600          ; retry
    1209600       ; expire
    {{ .Zone.TTL }} ) ; minimum
{{ range .Zone.NS }}
@ IN NS {{ . }}
{{- end }}
{{ range .PTRs }}
{{ .RelName }} IN PTR {{ .Target }}
{{- end }}
`))

// --- public API ---

// Sync writes a zone file for each configured zone and reloads NSD when the
// content changes. Forward and reverse zones are detected automatically by
// the zone name suffix (.in-addr.arpa / .ip6.arpa).
// It is safe to call repeatedly (idempotent).
func Sync(cfg Config, hosts []model.Host, dryRun, verbose bool) error {
	for _, zone := range cfg.Zones {
		if zone.TTL == 0 {
			zone.TTL = 3600
		}

		content, count, err := renderZone(zone, hosts)
		if err != nil {
			return fmt.Errorf("nsd: zone %s: %w", zone.Name, err)
		}

		path := filepath.Join(cfg.ZonesDir, zone.Name+".zone")

		if dryRun {
			existing, readErr := os.ReadFile(path)
			if readErr == nil && bytes.Equal(existing, content) {
				log.Printf("[dry-run] nsd: zone %s unchanged", zone.Name)
			} else {
				if readErr != nil {
					log.Printf("[dry-run] nsd: zone %s would be created (%d records)", zone.Name, count)
				} else {
					log.Printf("[dry-run] nsd: zone %s would be updated (%d records)", zone.Name, count)
				}
				if verbose {
					fmt.Print(unifiedDiff(path, existing, content))
				}
			}
			continue
		}

		changed, err := writeIfChanged(path, content)
		if err != nil {
			return fmt.Errorf("nsd: zone %s: write %s: %w", zone.Name, path, err)
		}

		if changed {
			log.Printf("nsd: zone %s updated (%d records)", zone.Name, count)
			if cfg.ReloadCmd != "" {
				cmd := cfg.ReloadCmd + " " + zone.Name
				if out, err := exec.Command("sh", "-c", cmd).CombinedOutput(); err != nil {
					log.Printf("nsd: reload error for %s: %v: %s", zone.Name, err, out)
				}
			}
		}
	}
	return nil
}

// --- rendering ---

func renderZone(zone ZoneConfig, hosts []model.Host) ([]byte, int, error) {
	var buf bytes.Buffer
	if isReverseZone(zone.Name) {
		ptrs := ptrEntriesForZone(hosts, zone.Name)
		serial := contentSerial(zone.Name, func(w io.Writer) {
			for _, p := range ptrs {
				_, _ = fmt.Fprintf(w, "%s\t%s\n", p.RelName, p.Target)
			}
		})
		err := reverseTmpl.Execute(&buf, reverseZoneData{Zone: zone, PTRs: ptrs, Serial: serial})
		return buf.Bytes(), len(ptrs), err
	}

	zoneHosts := hostsForZone(hosts, zone.Name)
	serial := contentSerial(zone.Name, func(w io.Writer) {
		for _, host := range zoneHosts {
			_, _ = fmt.Fprintf(w, "%s\t%s\t%s\n", host.Name, host.IPv4, host.IPv6)
		}
	})
	err := forwardTmpl.Execute(&buf, forwardZoneData{Zone: zone, Hosts: zoneHosts, Serial: serial})
	return buf.Bytes(), len(zoneHosts), err
}

// contentSerial returns a stable 32-bit FNV serial derived from the zone name
// and its current records. Identical content always produces the same serial,
// making zone files idempotent across runs.
func contentSerial(zoneName string, write func(io.Writer)) string {
	h := fnv.New32a()
	_, _ = fmt.Fprint(h, zoneName)
	write(h)
	return fmt.Sprintf("%d", h.Sum32())
}

// isReverseZone reports whether zone is a reverse DNS zone.
func isReverseZone(name string) bool {
	return strings.HasSuffix(name, ".in-addr.arpa") || strings.HasSuffix(name, ".ip6.arpa")
}

// hostsForZone returns hosts whose Name falls within the forward zone.
func hostsForZone(hosts []model.Host, zone string) []model.Host {
	var result []model.Host
	for _, h := range hosts {
		if h.Name == zone || strings.HasSuffix(h.Name, "."+zone) {
			result = append(result, h)
		}
	}
	return result
}

// ptrEntriesForZone returns PTR entries for all hosts whose IPs fall within
// the given reverse zone (either .in-addr.arpa or .ip6.arpa).
func ptrEntriesForZone(hosts []model.Host, zone string) []ptrEntry {
	var entries []ptrEntry
	for _, h := range hosts {
		target := h.Name + "."
		if h.IPv4 != nil {
			if rel, ok := ipv4PTRRelName(h.IPv4, zone); ok {
				entries = append(entries, ptrEntry{RelName: rel, Target: target})
			}
		}
		if h.IPv6 != nil {
			if rel, ok := ipv6PTRRelName(h.IPv6, zone); ok {
				entries = append(entries, ptrEntry{RelName: rel, Target: target})
			}
		}
	}
	return entries
}

// --- PTR name computation ---

// ipv4PTRRelName returns the owner name relative to a reverse zone like
// "1.168.192.in-addr.arpa" for an IPv4 address.
//
// Example: IP 192.168.1.10 in zone "1.168.192.in-addr.arpa" → "10"
//
//	IP 192.168.1.10 in zone "168.192.in-addr.arpa"   → "10.1"
func ipv4PTRRelName(ip net.IP, zone string) (string, bool) {
	v4 := ip.To4()
	if v4 == nil {
		return "", false
	}
	if !strings.HasSuffix(zone, ".in-addr.arpa") {
		return "", false
	}

	// Strip suffix to get the reversed octet prefix, e.g. "1.168.192"
	revOctets := strings.TrimSuffix(zone, ".in-addr.arpa")
	zoneParts := strings.Split(revOctets, ".")
	// Reverse to reconstruct the network prefix: ["192","168","1"]
	for i, j := 0, len(zoneParts)-1; i < j; i, j = i+1, j-1 {
		zoneParts[i], zoneParts[j] = zoneParts[j], zoneParts[i]
	}

	ipParts := strings.Split(v4.String(), ".")
	if len(zoneParts) >= len(ipParts) {
		return "", false
	}
	for i, p := range zoneParts {
		if ipParts[i] != p {
			return "", false
		}
	}

	// Remaining octets, reversed (PTR record order).
	remaining := append([]string(nil), ipParts[len(zoneParts):]...)
	for i, j := 0, len(remaining)-1; i < j; i, j = i+1, j-1 {
		remaining[i], remaining[j] = remaining[j], remaining[i]
	}
	return strings.Join(remaining, "."), true
}

// ipv6PTRRelName returns the owner name relative to a reverse zone like
// "0.0.1.0.8.b.d.0.1.0.0.2.ip6.arpa" for an IPv6 address.
//
// Example: 2001:db8:100::1 in zone "0.0.1.0.8.b.d.0.1.0.0.2.ip6.arpa"
//
//	→ "1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0"
func ipv6PTRRelName(ip net.IP, zone string) (string, bool) {
	v6 := ip.To16()
	if v6 == nil || ip.To4() != nil {
		return "", false
	}
	if !strings.HasSuffix(zone, ".ip6.arpa") {
		return "", false
	}

	// Build all 32 reversed nibbles.
	// nibbles[0] = low nibble of last byte, nibbles[31] = high nibble of first byte.
	nibbles := make([]string, 32)
	for i := 0; i < 16; i++ {
		b := v6[i]
		nibbles[31-2*i] = fmt.Sprintf("%x", b>>4)   // high nibble
		nibbles[30-2*i] = fmt.Sprintf("%x", b&0x0f) // low nibble
	}

	zoneNibbles := strings.TrimSuffix(zone, ".ip6.arpa")
	zoneCount := len(strings.Split(zoneNibbles, "."))
	if zoneCount > 32 {
		return "", false
	}

	// The last zoneCount nibbles must match the zone.
	suffix := strings.Join(nibbles[32-zoneCount:], ".")
	if suffix != zoneNibbles {
		return "", false
	}

	return strings.Join(nibbles[:32-zoneCount], "."), true
}

// unifiedDiff returns a unified diff string (diff -u format) between old and new.
// label is used as the filename in the header. Returns "" if content is identical.
func unifiedDiff(label string, old, new []byte) string {
	const ctx = 3

	splitLines := func(b []byte) []string {
		if len(b) == 0 {
			return nil
		}
		return strings.Split(strings.TrimRight(string(b), "\n"), "\n")
	}

	oldLines := splitLines(old)
	newLines := splitLines(new)
	edits := diffLines(oldLines, newLines)
	n := len(edits)

	var changed []int
	for i, e := range edits {
		if e.kind != ' ' {
			changed = append(changed, i)
		}
	}
	if len(changed) == 0 {
		return ""
	}

	type hunkRange struct{ lo, hi int }
	var ranges []hunkRange
	lo := max(0, changed[0]-ctx)
	hi := min(n, changed[0]+1+ctx)
	for _, idx := range changed[1:] {
		if max(0, idx-ctx) <= hi {
			hi = min(n, idx+1+ctx)
		} else {
			ranges = append(ranges, hunkRange{lo, hi})
			lo = max(0, idx-ctx)
			hi = min(n, idx+1+ctx)
		}
	}
	ranges = append(ranges, hunkRange{lo, hi})

	oldNums := make([]int, n)
	newNums := make([]int, n)
	ol, nl := 1, 1
	for i, e := range edits {
		oldNums[i] = ol
		newNums[i] = nl
		if e.kind != '+' {
			ol++
		}
		if e.kind != '-' {
			nl++
		}
	}

	var sb strings.Builder
	fmt.Fprintf(&sb, "--- %s (current)\n+++ %s (would be written)\n", label, label)
	for _, r := range ranges {
		oldCount, newCount := 0, 0
		for _, e := range edits[r.lo:r.hi] {
			if e.kind != '+' {
				oldCount++
			}
			if e.kind != '-' {
				newCount++
			}
		}
		fmt.Fprintf(&sb, "@@ -%d,%d +%d,%d @@\n", oldNums[r.lo], oldCount, newNums[r.lo], newCount)
		for _, e := range edits[r.lo:r.hi] {
			fmt.Fprintf(&sb, "%c%s\n", e.kind, e.line)
		}
	}
	return sb.String()
}

type diffEdit struct {
	kind rune // ' ' equal, '-' delete, '+' insert
	line string
}

// diffLines computes a line-by-line edit script using LCS.
func diffLines(a, b []string) []diffEdit {
	m, n := len(a), len(b)
	dp := make([][]int, m+1)
	for i := range dp {
		dp[i] = make([]int, n+1)
	}
	for i := 1; i <= m; i++ {
		for j := 1; j <= n; j++ {
			if a[i-1] == b[j-1] {
				dp[i][j] = dp[i-1][j-1] + 1
			} else if dp[i-1][j] >= dp[i][j-1] {
				dp[i][j] = dp[i-1][j]
			} else {
				dp[i][j] = dp[i][j-1]
			}
		}
	}
	var edits []diffEdit
	i, j := m, n
	for i > 0 || j > 0 {
		switch {
		case i > 0 && j > 0 && a[i-1] == b[j-1]:
			edits = append(edits, diffEdit{' ', a[i-1]})
			i--
			j--
		case j > 0 && (i == 0 || dp[i][j-1] >= dp[i-1][j]):
			edits = append(edits, diffEdit{'+', b[j-1]})
			j--
		default:
			edits = append(edits, diffEdit{'-', a[i-1]})
			i--
		}
	}
	for l, r := 0, len(edits)-1; l < r; l, r = l+1, r-1 {
		edits[l], edits[r] = edits[r], edits[l]
	}
	return edits
}

func writeIfChanged(path string, data []byte) (bool, error) {
	existing, err := os.ReadFile(path)
	if err == nil && bytes.Equal(existing, data) {
		return false, nil
	}
	return true, os.WriteFile(path, data, 0o644)
}
