package dhcpd

import (
	"bytes"
	"fmt"
	"log"
	"os"
	"os/exec"
	"strings"

	"github.com/sylgeist/dnstonetbox/internal/fileutil"
	"github.com/sylgeist/dnstonetbox/model"
)

// Netboot holds optional settings for emitting FreeBSD diskless netboot options
// (filename / root-path / next-server) for hosts that carry a DisklessArch.
type Netboot struct {
	NFSServer      string `yaml:"nfs_server"`      // required to enable netboot
	RootBase       string `yaml:"root_base"`       // default "/diskless/hosts"
	NextServer     string `yaml:"next_server"`     // optional; line omitted if empty
	LoaderFilename string `yaml:"loader_filename"` // default "{arch}/loader.efi"
}

// Config holds DHCPD generator settings.
type Config struct {
	ConfigFile string   `yaml:"config_file"` // path to generated include file
	ReloadCmd  string   `yaml:"reload_cmd"`  // e.g. "rcctl restart dhcpd"
	Netboot    *Netboot `yaml:"netboot"`     // optional; nil disables netboot options
}

// Sync writes an OpenBSD dhcpd static-host include file and reloads dhcpd
// when the content changes. Include this file from dhcpd.conf with:
//
//	include "/path/to/static-hosts.conf";
//
// Only hosts with both a MAC address and an IPv4 address are emitted.
// It is safe to call repeatedly (idempotent).
func Sync(cfg Config, hosts []model.Host, dryRun, verbose bool) error {
	if cfg.ConfigFile == "" {
		return nil
	}

	var buf bytes.Buffer
	fmt.Fprintln(&buf, "# Generated by dnstonetbox — do not edit manually")

	nb := cfg.Netboot
	netbootActive := nb != nil && nb.NFSServer != ""
	rootBase := "/diskless/hosts"
	loaderTmpl := "{arch}/loader.efi"
	if nb != nil {
		if nb.RootBase != "" {
			rootBase = strings.TrimRight(nb.RootBase, "/")
		}
		if nb.LoaderFilename != "" {
			loaderTmpl = nb.LoaderFilename
		}
	}

	count := 0
	for _, h := range hosts {
		if h.MAC == "" || h.IPv4 == nil {
			continue
		}
		// The host declaration name must be unique across the file, so use the
		// full FQDN (NetBox dns_name is unique per host). The first DNS label is
		// the short hostname handed to the client via the host-name option.
		label := strings.SplitN(h.Name, ".", 2)[0]
		fmt.Fprintf(&buf, "\nhost %s {\n", h.Name)
		fmt.Fprintf(&buf, "\thardware ethernet %s;\n", h.MAC)
		fmt.Fprintf(&buf, "\tfixed-address %s;\n", h.IPv4)
		fmt.Fprintf(&buf, "\toption host-name \"%s\";\n", label)
		if h.DisklessArch != "" {
			if netbootActive {
				loader := strings.ReplaceAll(loaderTmpl, "{arch}", h.DisklessArch)
				fmt.Fprintf(&buf, "\tfilename \"%s\";\n", loader)
				// root-path uses the short label (not the FQDN) because it must match
				// the diskless server's per-host dataset, e.g. nova/diskless/hosts/<label>.
				// Assumes the first DNS label is unique among diskless hosts (true within
				// a single domain); hosts sharing a leftmost label across zones would
				// collide on the same root path.
				fmt.Fprintf(&buf, "\toption root-path \"%s:%s/%s\";\n", nb.NFSServer, rootBase, label)
				if nb.NextServer != "" {
					fmt.Fprintf(&buf, "\tnext-server %s;\n", nb.NextServer)
				}
			} else {
				log.Printf("dhcpd: host %s has diskless_arch=%q but dhcpd.netboot is not configured; emitting plain host", h.Name, h.DisklessArch)
			}
		}
		fmt.Fprintln(&buf, "}")
		count++
	}

	content := buf.Bytes()

	if dryRun {
		existing, readErr := os.ReadFile(cfg.ConfigFile)
		if readErr == nil && bytes.Equal(existing, content) {
			log.Printf("[dry-run] dhcpd: %s unchanged", cfg.ConfigFile)
		} else {
			if readErr != nil {
				log.Printf("[dry-run] dhcpd: %s would be created (%d static hosts)", cfg.ConfigFile, count)
			} else {
				log.Printf("[dry-run] dhcpd: %s would be updated (%d static hosts)", cfg.ConfigFile, count)
			}
			if verbose {
				fmt.Print(fileutil.UnifiedDiff(cfg.ConfigFile, existing, content))
			}
		}
		return nil
	}

	changed, err := fileutil.WriteIfChanged(cfg.ConfigFile, content)
	if err != nil {
		return fmt.Errorf("dhcpd: write %s: %w", cfg.ConfigFile, err)
	}

	if changed {
		log.Printf("dhcpd: config updated (%d static hosts)", count)
		if cfg.ReloadCmd != "" {
			if out, err := exec.Command("sh", "-c", cfg.ReloadCmd).CombinedOutput(); err != nil {
				log.Printf("dhcpd: reload error: %v: %s", err, out)
			}
		}
	}
	return nil
}
