package dhcpd

import (
	"bytes"
	"fmt"
	"log"
	"os"
	"os/exec"
	"strings"

	"github.com/sylgeist/dnstonetbox/model"
)

// Config holds DHCPD generator settings.
type Config struct {
	ConfigFile string `yaml:"config_file"` // path to generated include file
	ReloadCmd  string `yaml:"reload_cmd"`  // e.g. "rcctl restart dhcpd"
}

// Sync writes an OpenBSD dhcpd static-host include file and reloads dhcpd
// when the content changes. Include this file from dhcpd.conf with:
//
//	include "/path/to/static-hosts.conf";
//
// Only hosts with both a MAC address and an IPv4 address are emitted.
// It is safe to call repeatedly (idempotent).
func Sync(cfg Config, hosts []model.Host) error {
	if cfg.ConfigFile == "" {
		return nil
	}

	var buf bytes.Buffer
	fmt.Fprintln(&buf, "# Generated by dnstonetbox — do not edit manually")

	count := 0
	for _, h := range hosts {
		if h.MAC == "" || h.IPv4 == nil {
			continue
		}
		// Use the first DNS label as the host identifier in dhcpd.conf.
		label := strings.SplitN(h.Name, ".", 2)[0]
		fmt.Fprintf(&buf, "\nhost %s {\n", label)
		fmt.Fprintf(&buf, "\thardware ethernet %s;\n", h.MAC)
		fmt.Fprintf(&buf, "\tfixed-address %s;\n", h.IPv4)
		fmt.Fprintf(&buf, "\toption host-name \"%s\";\n", label)
		fmt.Fprintln(&buf, "}")
		count++
	}

	changed, err := writeIfChanged(cfg.ConfigFile, buf.Bytes())
	if err != nil {
		return fmt.Errorf("dhcpd: write %s: %w", cfg.ConfigFile, err)
	}

	if changed {
		log.Printf("dhcpd: config updated (%d static hosts)", count)
		if cfg.ReloadCmd != "" {
			if out, err := exec.Command("sh", "-c", cfg.ReloadCmd).CombinedOutput(); err != nil {
				log.Printf("dhcpd: reload error: %v: %s", err, out)
			}
		}
	}
	return nil
}

func writeIfChanged(path string, data []byte) (bool, error) {
	existing, err := os.ReadFile(path)
	if err == nil && bytes.Equal(existing, data) {
		return false, nil
	}
	return true, os.WriteFile(path, data, 0o644)
}
