package unbound

import (
	"bytes"
	"fmt"
	"log"
	"os"
	"os/exec"

	"github.com/sseekamp/dnstonetbox/model"
)

// Config holds Unbound generator settings.
type Config struct {
	ConfigFile string `yaml:"config_file"` // path to generated include file
	ReloadCmd  string `yaml:"reload_cmd"`  // e.g. "unbound-control reload"
	TTL        int    `yaml:"ttl"`         // default 3600
}

// Sync writes an Unbound local-data include file and reloads Unbound when
// the content changes. Include this file from unbound.conf with:
//
//	include: /path/to/local-hosts.conf
//
// It is safe to call repeatedly (idempotent).
func Sync(cfg Config, hosts []model.Host) error {
	if cfg.ConfigFile == "" {
		return nil
	}

	ttl := cfg.TTL
	if ttl == 0 {
		ttl = 3600
	}

	var buf bytes.Buffer
	fmt.Fprintln(&buf, "# Generated by dnstonetbox — do not edit manually")
	for _, h := range hosts {
		fqdn := h.Name + "."
		if h.IPv4 != nil {
			fmt.Fprintf(&buf, "local-data: \"%s %d IN A %s\"\n", fqdn, ttl, h.IPv4)
			fmt.Fprintf(&buf, "local-data-ptr: \"%s %d %s\"\n", h.IPv4, ttl, fqdn)
		}
		if h.IPv6 != nil {
			fmt.Fprintf(&buf, "local-data: \"%s %d IN AAAA %s\"\n", fqdn, ttl, h.IPv6)
			fmt.Fprintf(&buf, "local-data-ptr: \"%s %d %s\"\n", h.IPv6, ttl, fqdn)
		}
	}

	changed, err := writeIfChanged(cfg.ConfigFile, buf.Bytes())
	if err != nil {
		return fmt.Errorf("unbound: write %s: %w", cfg.ConfigFile, err)
	}

	if changed {
		log.Printf("unbound: config updated (%d hosts)", len(hosts))
		if cfg.ReloadCmd != "" {
			if out, err := exec.Command("sh", "-c", cfg.ReloadCmd).CombinedOutput(); err != nil {
				log.Printf("unbound: reload error: %v: %s", err, out)
			}
		}
	}
	return nil
}

func writeIfChanged(path string, data []byte) (bool, error) {
	existing, err := os.ReadFile(path)
	if err == nil && bytes.Equal(existing, data) {
		return false, nil
	}
	return true, os.WriteFile(path, data, 0o644)
}
