package unbound

import (
	"bytes"
	"fmt"
	"log"
	"os"
	"os/exec"

	"github.com/sylgeist/dnstonetbox/internal/fileutil"
	"github.com/sylgeist/dnstonetbox/model"
)

// Config holds Unbound generator settings.
type Config struct {
	ConfigFile string `yaml:"config_file"` // path to generated include file
	ReloadCmd  string `yaml:"reload_cmd"`  // e.g. "unbound-control reload"
	TTL        int    `yaml:"ttl"`         // default 3600
}

// Sync writes an Unbound local-data include file and reloads Unbound when
// the content changes. Include this file from unbound.conf with:
//
//	include: /path/to/local-hosts.conf
//
// It is safe to call repeatedly (idempotent).
func Sync(cfg Config, hosts []model.Host, dryRun, verbose bool) error {
	if cfg.ConfigFile == "" {
		return nil
	}

	ttl := cfg.TTL
	if ttl == 0 {
		ttl = 3600
	}

	var buf bytes.Buffer
	fmt.Fprintln(&buf, "# Generated by dnstonetbox — do not edit manually")
	for _, h := range hosts {
		fqdn := h.Name + "."
		if h.IPv4 != nil {
			fmt.Fprintf(&buf, "local-data: \"%s %d IN A %s\"\n", fqdn, ttl, h.IPv4)
			fmt.Fprintf(&buf, "local-data-ptr: \"%s %d %s\"\n", h.IPv4, ttl, fqdn)
		}
		if h.IPv6 != nil {
			fmt.Fprintf(&buf, "local-data: \"%s %d IN AAAA %s\"\n", fqdn, ttl, h.IPv6)
			fmt.Fprintf(&buf, "local-data-ptr: \"%s %d %s\"\n", h.IPv6, ttl, fqdn)
		}
	}

	content := buf.Bytes()

	if dryRun {
		existing, readErr := os.ReadFile(cfg.ConfigFile)
		if readErr == nil && bytes.Equal(existing, content) {
			log.Printf("[dry-run] unbound: %s unchanged", cfg.ConfigFile)
		} else {
			if readErr != nil {
				log.Printf("[dry-run] unbound: %s would be created (%d hosts)", cfg.ConfigFile, len(hosts))
			} else {
				log.Printf("[dry-run] unbound: %s would be updated (%d hosts)", cfg.ConfigFile, len(hosts))
			}
			if verbose {
				fmt.Print(fileutil.UnifiedDiff(cfg.ConfigFile, existing, content))
			}
		}
		return nil
	}

	changed, err := fileutil.WriteIfChanged(cfg.ConfigFile, content)
	if err != nil {
		return fmt.Errorf("unbound: write %s: %w", cfg.ConfigFile, err)
	}

	if changed {
		log.Printf("unbound: config updated (%d hosts)", len(hosts))
		if cfg.ReloadCmd != "" {
			if out, err := exec.Command("sh", "-c", cfg.ReloadCmd).CombinedOutput(); err != nil {
				log.Printf("unbound: reload error: %v: %s", err, out)
			}
		}
	}
	return nil
}
