package unbound

import (
	"bytes"
	"fmt"
	"log"
	"os"
	"os/exec"
	"strings"

	"github.com/sylgeist/dnstonetbox/model"
)

// Config holds Unbound generator settings.
type Config struct {
	ConfigFile string `yaml:"config_file"` // path to generated include file
	ReloadCmd  string `yaml:"reload_cmd"`  // e.g. "unbound-control reload"
	TTL        int    `yaml:"ttl"`         // default 3600
}

// Sync writes an Unbound local-data include file and reloads Unbound when
// the content changes. Include this file from unbound.conf with:
//
//	include: /path/to/local-hosts.conf
//
// It is safe to call repeatedly (idempotent).
func Sync(cfg Config, hosts []model.Host, dryRun, verbose bool) error {
	if cfg.ConfigFile == "" {
		return nil
	}

	ttl := cfg.TTL
	if ttl == 0 {
		ttl = 3600
	}

	var buf bytes.Buffer
	fmt.Fprintln(&buf, "# Generated by dnstonetbox — do not edit manually")
	for _, h := range hosts {
		fqdn := h.Name + "."
		if h.IPv4 != nil {
			fmt.Fprintf(&buf, "local-data: \"%s %d IN A %s\"\n", fqdn, ttl, h.IPv4)
			fmt.Fprintf(&buf, "local-data-ptr: \"%s %d %s\"\n", h.IPv4, ttl, fqdn)
		}
		if h.IPv6 != nil {
			fmt.Fprintf(&buf, "local-data: \"%s %d IN AAAA %s\"\n", fqdn, ttl, h.IPv6)
			fmt.Fprintf(&buf, "local-data-ptr: \"%s %d %s\"\n", h.IPv6, ttl, fqdn)
		}
	}

	content := buf.Bytes()

	if dryRun {
		existing, readErr := os.ReadFile(cfg.ConfigFile)
		if readErr == nil && bytes.Equal(existing, content) {
			log.Printf("[dry-run] unbound: %s unchanged", cfg.ConfigFile)
		} else {
			if readErr != nil {
				log.Printf("[dry-run] unbound: %s would be created (%d hosts)", cfg.ConfigFile, len(hosts))
			} else {
				log.Printf("[dry-run] unbound: %s would be updated (%d hosts)", cfg.ConfigFile, len(hosts))
			}
			if verbose {
				fmt.Print(unifiedDiff(cfg.ConfigFile, existing, content))
			}
		}
		return nil
	}

	changed, err := writeIfChanged(cfg.ConfigFile, content)
	if err != nil {
		return fmt.Errorf("unbound: write %s: %w", cfg.ConfigFile, err)
	}

	if changed {
		log.Printf("unbound: config updated (%d hosts)", len(hosts))
		if cfg.ReloadCmd != "" {
			if out, err := exec.Command("sh", "-c", cfg.ReloadCmd).CombinedOutput(); err != nil {
				log.Printf("unbound: reload error: %v: %s", err, out)
			}
		}
	}
	return nil
}

func unifiedDiff(label string, old, new []byte) string {
	const ctx = 3

	splitLines := func(b []byte) []string {
		if len(b) == 0 {
			return nil
		}
		return strings.Split(strings.TrimRight(string(b), "\n"), "\n")
	}

	oldLines := splitLines(old)
	newLines := splitLines(new)
	edits := diffLines(oldLines, newLines)
	n := len(edits)

	var changed []int
	for i, e := range edits {
		if e.kind != ' ' {
			changed = append(changed, i)
		}
	}
	if len(changed) == 0 {
		return ""
	}

	type hunkRange struct{ lo, hi int }
	var ranges []hunkRange
	lo := max(0, changed[0]-ctx)
	hi := min(n, changed[0]+1+ctx)
	for _, idx := range changed[1:] {
		if max(0, idx-ctx) <= hi {
			hi = min(n, idx+1+ctx)
		} else {
			ranges = append(ranges, hunkRange{lo, hi})
			lo = max(0, idx-ctx)
			hi = min(n, idx+1+ctx)
		}
	}
	ranges = append(ranges, hunkRange{lo, hi})

	oldNums := make([]int, n)
	newNums := make([]int, n)
	ol, nl := 1, 1
	for i, e := range edits {
		oldNums[i] = ol
		newNums[i] = nl
		if e.kind != '+' {
			ol++
		}
		if e.kind != '-' {
			nl++
		}
	}

	var sb strings.Builder
	fmt.Fprintf(&sb, "--- %s (current)\n+++ %s (would be written)\n", label, label)
	for _, r := range ranges {
		oldCount, newCount := 0, 0
		for _, e := range edits[r.lo:r.hi] {
			if e.kind != '+' {
				oldCount++
			}
			if e.kind != '-' {
				newCount++
			}
		}
		fmt.Fprintf(&sb, "@@ -%d,%d +%d,%d @@\n", oldNums[r.lo], oldCount, newNums[r.lo], newCount)
		for _, e := range edits[r.lo:r.hi] {
			fmt.Fprintf(&sb, "%c%s\n", e.kind, e.line)
		}
	}
	return sb.String()
}

type diffEdit struct {
	kind rune
	line string
}

func diffLines(a, b []string) []diffEdit {
	m, n := len(a), len(b)
	dp := make([][]int, m+1)
	for i := range dp {
		dp[i] = make([]int, n+1)
	}
	for i := 1; i <= m; i++ {
		for j := 1; j <= n; j++ {
			if a[i-1] == b[j-1] {
				dp[i][j] = dp[i-1][j-1] + 1
			} else if dp[i-1][j] >= dp[i][j-1] {
				dp[i][j] = dp[i-1][j]
			} else {
				dp[i][j] = dp[i][j-1]
			}
		}
	}
	var edits []diffEdit
	i, j := m, n
	for i > 0 || j > 0 {
		switch {
		case i > 0 && j > 0 && a[i-1] == b[j-1]:
			edits = append(edits, diffEdit{' ', a[i-1]})
			i--
			j--
		case j > 0 && (i == 0 || dp[i][j-1] >= dp[i-1][j]):
			edits = append(edits, diffEdit{'+', b[j-1]})
			j--
		default:
			edits = append(edits, diffEdit{'-', a[i-1]})
			i--
		}
	}
	for l, r := 0, len(edits)-1; l < r; l, r = l+1, r-1 {
		edits[l], edits[r] = edits[r], edits[l]
	}
	return edits
}

func writeIfChanged(path string, data []byte) (bool, error) {
	existing, err := os.ReadFile(path)
	if err == nil && bytes.Equal(existing, data) {
		return false, nil
	}
	return true, os.WriteFile(path, data, 0o644)
}
